// Generated by Melange
'use strict';

var React = require("react");
var Belt_List = require("melange/lib/js/belt_List.js");
var ReactDom = require("react-dom");

function ReactApp$App(Props) {
  return Belt_List.toArray(Belt_List.map({
                  hd: "Hello world!",
                  tl: {
                    hd: "This is React!",
                    tl: /* [] */0
                  }
                }, (function (greeting) {
                    return React.createElement("h1", undefined, greeting);
                  })));
}

var App = {
  make: ReactApp$App
};

var root = document.querySelector("#root");

if (root == null) {
  console.error("Failed to start React: couldn't find the #root element");
} else {
  ReactDom.render(React.createElement(ReactApp$App, {}), root);
}

exports.App = App;
/* root Not a pure module */
